-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 12:28:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PortfolioPersonal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PortfolioPersonal` ;

-- -----------------------------------------------------
-- Schema PortfolioPersonal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PortfolioPersonal` DEFAULT CHARACTER SET utf8 ;
USE `PortfolioPersonal` ;

-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Profesion` VARCHAR(45) NULL,
  `AcercaDe` VARCHAR(200) NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Banner` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`RedSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`RedSocial` (
  `IdRedSocial` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Logo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdRedSocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`Experiencia` (
  `idExperiencia` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `Empresa` VARCHAR(45) NOT NULL,
  `Desde` DATE NULL,
  `Hasta` DATE NULL,
  `Puesto` VARCHAR(60) NULL,
  `Tareas` VARCHAR(240) NULL,
  `LogoEmpresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idExperiencia`),
  CONSTRAINT `fk_Experiencia_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `PortfolioPersonal`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Experiencia_Persona1_idx` ON `PortfolioPersonal`.`Experiencia` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`ClaseFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`ClaseFormacion` (
  `IdClase` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdClase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`Formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`Formacion` (
  `idFormacion` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Fecha` DATE NULL,
  `Institucion` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `idPersona` INT NOT NULL,
  `idClaseForm` INT NOT NULL,
  PRIMARY KEY (`idFormacion`),
  CONSTRAINT `fk_Formacion_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `PortfolioPersonal`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formacion_ClaseFormacion1`
    FOREIGN KEY (`idClaseForm`)
    REFERENCES `PortfolioPersonal`.`ClaseFormacion` (`IdClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Formacion_Persona1_idx` ON `PortfolioPersonal`.`Formacion` (`idPersona` ASC) VISIBLE;

CREATE INDEX `fk_Formacion_ClaseFormacion1_idx` ON `PortfolioPersonal`.`Formacion` (`idClaseForm` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`Skills` (
  `idSkill` INT NOT NULL AUTO_INCREMENT,
  `SkillDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSkill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`Proyectos` (
  `idProyectos` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `NombreProyecto` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `LinkProyecto` VARCHAR(60) NULL,
  PRIMARY KEY (`idProyectos`),
  CONSTRAINT `fk_Proyectos_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `PortfolioPersonal`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Proyectos_Persona1_idx` ON `PortfolioPersonal`.`Proyectos` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`RedesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`RedesSociales` (
  `idSocialRed` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `LinkRedSocial` VARCHAR(60) NULL,
  PRIMARY KEY (`idSocialRed`, `idPersona`),
  CONSTRAINT `fk_RedesSociales_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `PortfolioPersonal`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RedesSociales_RedSocial1`
    FOREIGN KEY (`idSocialRed`)
    REFERENCES `PortfolioPersonal`.`RedSocial` (`IdRedSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RedesSociales_Persona_idx` ON `PortfolioPersonal`.`RedesSociales` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PortfolioPersonal`.`SkillPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioPersonal`.`SkillPersona` (
  `idSkillPersona` INT NOT NULL AUTO_INCREMENT,
  `idSkill` INT NOT NULL,
  `SkillLevel` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idSkillPersona`),
  CONSTRAINT `fk_SkillPersona_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `PortfolioPersonal`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SkillPersona_Skills1`
    FOREIGN KEY (`idSkill`)
    REFERENCES `PortfolioPersonal`.`Skills` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SkillPersona_Persona1_idx` ON `PortfolioPersonal`.`SkillPersona` (`idPersona` ASC) VISIBLE;

CREATE INDEX `fk_SkillPersona_Skills1_idx` ON `PortfolioPersonal`.`SkillPersona` (`idSkill` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
